version: 2
updates:
  - package-ecosystem: "bun"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      docusaurus:
        patterns:
          - "@docusaurus/*"
    ignore:
      - dependency-name: "p5"
        versions:
          - ">=2.0.0" # Ignore version 2.0+ until official release
