[project]
name = "documentation"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "nbconvert>=7.16.6",
    "nbformat>=5.10.4",
]

[dependency-groups]
dev = [
    "matplotlib>=3.10.1",
    "numpy>=2.2.4",
    "pytest>=8.3.5",
]
