name: Test Notebook Convert

on:
  push:
    paths:
      - 'scripts/notebook_*.py'
      - 'scripts/notebook_convert_templates/**'
      - 'tests/test-notebook-convert.py'
      - '.github/workflows/test-notebook-convert.yml'
  pull_request:
    paths:
      - 'scripts/notebook_*.py'
      - 'scripts/notebook_convert_templates/**'
      - 'tests/test-notebook-convert.py'
      - '.github/workflows/test-notebook-convert.yml'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest nbformat nbconvert matplotlib numpy
        
    - name: Run tests
      run: |
        pytest tests/test-notebook-convert.py -v
