name: Test notebook conversion

on:
  push:
    paths:
      - 'scripts/notebook_*.py'
      - 'scripts/notebook_convert_templates/**'
      - 'tests/test-notebook-convert.py'
      - '.github/workflows/test-notebook-convert.yml'
  pull_request:
    paths:
      - 'scripts/notebook_*.py'
      - 'scripts/notebook_convert_templates/**'
      - 'tests/test-notebook-convert.py'
      - '.github/workflows/test-notebook-convert.yml'
  workflow_dispatch:

jobs:
  test-convert:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        
    - name: Install Python dependencies
      run: |
        uv sync
        uv add pytest matplotlib numpy
        
    - name: Run tests
      run: |
        uvx pytest tests/test-notebook-convert.py -v
